version: "3.9"
services:
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - './.srv/database:/var/lib/mysql'
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: www
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  wordpress:
    image: wordpress:latest
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '8080:80'
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: www
      WORDPRESS_DEBUG: 1
    volumes:
      - './.srv/wordpress/:/var/www/html/'
      - './theme/:/var/www/html/wp-content/themes/custom-theme'
      - './plugin/:/var/www/html/wp-content/plugins/custom-plugin'
      - './.srv/custom.ini:/usr/local/etc/php/conf.d/custom.ini'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    depends_on:
      - mysql
    links:
      - mysql
    ports:
      - '8081:80'
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
  mailhog:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./data:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
